### ISSUE TITLE
wont install

### ISSUE THREAD

**Issue by techpulse** [PlitherProject/Plither#16]
i ran the installer..

[root@slither-01 Plither]# ./install_modules.sh
[BATCH] Installing server modules
[BATCH] Install complete, have fun!

`module.js:340
    throw err;
          ^
Error: Cannot find module 'geoip-lite'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/Plither/src/web/app.js:5:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
-------------------------------------------------------
[BATCH] Client Shutdown, waiting 15 seconds before a restart`

**Comment by techpulse** [comment]
@ItzLevvie 

``[root@slither-01 Plither]# npm install geoip-lite -d
npm info it worked if it ends with ok
npm info using npm@1.4.21
npm info using node@v0.10.30
npm info addNameTag [ 'geoip-lite', 'latest' ]
npm info trying registry request attempt 1 at 12:15:31
npm http GET https://registry.npmjs.org/geoip-lite
npm http 304 https://registry.npmjs.org/geoip-lite
npm info install geoip-lite@1.1.7 into /root/Plither
npm info installOne geoip-lite@1.1.7
npm info preuninstall geoip-lite@1.1.7
npm info uninstall geoip-lite@1.1.7
npm info postuninstall geoip-lite@1.1.7
Killed
`
